name = "ApiExample"
uuid = "3fb5a60c-7cec-46b5-b009-7d1216915f35"
authors = ["Matt Helm"]
version = "0.1.0"

[deps]
Genie = "c43c736e-a2d1-11e8-161f-af95117fbd1e"

[compat]
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
